# Generated by Django 4.0.5 on 2022-07-03 13:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='balance',
            field=models.IntegerField(default=0, verbose_name='Баланс'),
        ),
        migrations.AddField(
            model_name='profile',
            name='city',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.PROTECT, to='shop.city', verbose_name='Город'),
        ),
    ]
