# Generated by Django 4.0.5 on 2022-07-03 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0004_profile_balance_profile_city'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='slug',
            field=models.SlugField(default='<django.db.models.query_utils.DeferredAttribute object at 0x0000022AA88D6DF0>', max_length=255, unique=True, verbose_name='URL'),
        ),
    ]
